### ISSUE TITLE
Will this do lunar flashes as well as Jupiter and Saturn?

### ISSUE THREAD

**Issue by Plutonium5793** [DeTeCt-PSWS/DeTeCt-MFC#1]
I am sorry.  I know this isn't an issue, but I could not find a place to ask the question.  Your instructions seem to say that it only does Jupiter and  Saturn and I have been looking for one that does the moon.  Thanks,
John

**Comment by MarcDelcroix** [comment]
Unfortunatelyy detecting lunar flashes would need a different method. RoI detection / alignment would not work as lunar flash detections are done over the night side, and the image could contain only part of the night side. Furthermore some threshold used in the code are only valid for illuminated surfaces.
